const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
function database(env){if(!env.DB)throw Error('D1 unavailable');return env.DB;}
function validConfig(c){return c&&['kids','beginner','challenge'].includes(c.difficulty)&&['all','food','plastic','tricky'].includes(c.topic)&&['challenge','practice'].includes(c.mode);}
function matches(i,c){return (c.difficulty==='kids'?!i.h:c.difficulty==='challenge'?i.h:true)&&(c.topic==='food'?['food','trash'].includes(i.a):c.topic==='plastic'?['plastic','vinyl'].includes(i.a):c.topic==='tricky'?i.h:true);}
async function body(request){const raw=await request.text();if(raw.length>4096)throw Error('Body too large');return JSON.parse(raw);}
async function room(db,code){const r=await db.prepare('SELECT * FROM rooms WHERE code=?').bind(code).first();return r?{code:r.code,config:JSON.parse(r.config),items:JSON.parse(r.items),total:r.total}:null;}
export default {async fetch(request,env){const u=new URL(request.url),path=u.pathname;
if(path.startsWith('/api/')){try{const db=database(env);if(request.method==='POST'&&request.headers.get('origin')!==u.origin)return json({error:'Origin'},403);
if(path==='/api/rooms'&&request.method==='POST'){const b=await body(request);if(!validConfig(b.config)||(!Number.isInteger(b.total)||b.total<1||b.total>30)||!Array.isArray(b.items)||b.items.length!==b.total||new Set(b.items).size!==b.total||b.items.some(i=>!Number.isInteger(i)||!CATALOG[i]||!matches(CATALOG[i],b.config)))return json({error:'Invalid room'},400);for(let attempt=0;attempt<3;attempt++){const code=Array.from(crypto.getRandomValues(new Uint8Array(6)),x=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[x%32]).join('');try{await db.prepare('INSERT INTO rooms (code,config,items,total,created) VALUES (?,?,?,?,?)').bind(code,JSON.stringify(b.config),JSON.stringify(b.items),b.total,Date.now()).run();return json({code,config:b.config,items:b.items,total:b.total});}catch(e){if(attempt===2)throw e;}}}
const match=path.match(/^\/api\/rooms\/([A-Z2-9]{6})(\/ranking)?$/);if(match&&request.method==='GET'){const found=await room(db,match[1]);if(!found)return json({error:'Not found'},404);if(match[2]){const rows=await db.prepare('SELECT name,score,correct,total FROM scores WHERE room=? ORDER BY score DESC,correct DESC,created ASC,id ASC LIMIT 50').bind(found.code).all();return json(rows.results);}return json(found);}
if(path==='/api/ranking'&&request.method==='GET'){const total=Number(u.searchParams.get('total'));if(![5,10,20,30].includes(total))return json({error:'Invalid count'},400);const rows=await db.prepare('SELECT name,score,correct,total FROM scores WHERE total=? AND room IS NULL ORDER BY score DESC,correct DESC,created ASC,id ASC LIMIT 50').bind(total).all();return json(rows.results);}
if(path==='/api/ranking'&&request.method==='POST'){const b=await body(request),name=typeof b.name==='string'?b.name.trim():'';if(b.consent!==true||!name||name.length>12||/[<>\u0000-\u001f]/.test(name)||typeof b.id!=='string'||!/^[-a-f0-9]{36}$/.test(b.id)||(!Number.isInteger(b.total)||b.total<1||b.total>30)||!Number.isInteger(b.score)||!Number.isInteger(b.correct)||b.correct<0||b.correct>b.total||b.score<b.correct*100||b.score>b.correct*250)return json({error:'Invalid record'},400);let code=null;if(b.room){if(typeof b.room!=='string'||!/^[A-Z2-9]{6}$/.test(b.room))return json({error:'Invalid code'},400);const found=await room(db,b.room);if(!found||found.total!==b.total||found.config.mode!=='challenge')return json({error:'Invalid room'},400);code=found.code;}await db.prepare('INSERT INTO scores (id,name,score,correct,total,created,room) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(b.id,name,b.score,b.correct,b.total,Date.now(),code).run();return json({saved:true});}return json({error:'Not found'},404);
}catch(error){console.error('Game API failed',error);return json({error:'Unavailable'},503);}}
if(path==='/'||path==='/index.html')return new Response(PAGE,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-cache'}});
if(SOUNDS[path])return new Response(Uint8Array.from(atob(SOUNDS[path]),c=>c.charCodeAt(0)),{headers:{'content-type':'audio/wav','cache-control':'public,max-age=86400'}});
if(path==='/assets/heyi-avatar.png')return new Response(Uint8Array.from(atob(AVATAR),c=>c.charCodeAt(0)),{headers:{'content-type':'image/png','cache-control':'public,max-age=86400'}});return new Response('Not found',{status:404});}};
